### ISSUE TITLE
Update to 2.8x required

### ISSUE THREAD

**Issue by Tazshelby2016** [leafar-tb/proc-fruits#1]
This program does not work for 2.8x versions.

**Comment by leafar-tb** [comment]
I'm taking a look at upgrading it, but might me take some time.

**Comment by Tazshelby2016** [comment]
To be expected

**Comment by leafar-tb** [comment]
Should be compatible now, though I discovered some issues, that still need to be sorted out. (Generation/ mutation sometimes fails.)

**Comment by Tazshelby2016** [comment]
Thank you.
